"""Initial schema

Revision ID: 02b0cf6de6ea
Revises: 
Create Date: 2026-09-05 13:43:48.294539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b0cf6de6ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundamental_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roce', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('debt', sa.Float(), nullable=True),
    sa.Column('freeCashFlow', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundamental_snapshots_symbol'), 'fundamental_snapshots', ['symbol'], unique=False)
    op.create_index(op.f('ix_fundamental_snapshots_timestamp'), 'fundamental_snapshots', ['timestamp'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('percentageChange', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('marketCap', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_symbol'), 'market_snapshots', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_snapshots_timestamp'), 'market_snapshots', ['timestamp'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('publishedAt', sa.DateTime(), nullable=True),
    sa.Column('fetchedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_symbol'), 'news_articles', ['symbol'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('watchlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_userId'), 'watchlists', ['userId'], unique=False)
    op.create_table('watchlist_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('watchlistId', sa.String(length=36), nullable=False),
    sa.Column('lastCheckedAt', sa.DateTime(), nullable=False),
    sa.Column('thesisChangedCount', sa.Integer(), nullable=False),
    sa.Column('needsAttentionCount', sa.Integer(), nullable=False),
    sa.Column('noChangeCount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['watchlistId'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_evaluations_watchlistId'), 'watchlist_evaluations', ['watchlistId'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('watchlistId', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('companyName', sa.String(length=200), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['watchlistId'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlistId', 'symbol', name='uq_watchlist_symbol')
    )
    op.create_index(op.f('ix_watchlist_items_symbol'), 'watchlist_items', ['symbol'], unique=False)
    op.create_index(op.f('ix_watchlist_items_watchlistId'), 'watchlist_items', ['watchlistId'], unique=False)
    op.create_table('theses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('watchlistItemId', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('lastEvaluatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlistItemId'], ['watchlist_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theses_userId'), 'theses', ['userId'], unique=False)
    op.create_index(op.f('ix_theses_watchlistItemId'), 'theses', ['watchlistItemId'], unique=True)
    op.create_table('evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thesisId', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('supportingCount', sa.Integer(), nullable=False),
    sa.Column('contradictingCount', sa.Integer(), nullable=False),
    sa.Column('neutralCount', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evaluatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thesisId'], ['theses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_evaluatedAt'), 'evaluations', ['evaluatedAt'], unique=False)
    op.create_index(op.f('ix_evaluations_thesisId'), 'evaluations', ['thesisId'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thesisId', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('signalName', sa.String(length=150), nullable=False),
    sa.Column('sourceType', sa.String(length=50), nullable=False),
    sa.Column('sourceId', sa.String(length=100), nullable=True),
    sa.Column('previousValue', sa.String(length=255), nullable=True),
    sa.Column('currentValue', sa.String(length=255), nullable=True),
    sa.Column('changeValue', sa.String(length=255), nullable=True),
    sa.Column('changePercentage', sa.Float(), nullable=True),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thesisId'], ['theses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_symbol'), 'evidence', ['symbol'], unique=False)
    op.create_index(op.f('ix_evidence_thesisId'), 'evidence', ['thesisId'], unique=False)
    op.create_index(op.f('ix_evidence_timestamp'), 'evidence', ['timestamp'], unique=False)
    op.create_table('news_relevance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('newsArticleId', sa.String(length=36), nullable=False),
    sa.Column('thesisId', sa.String(length=36), nullable=False),
    sa.Column('relevanceScore', sa.Float(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['newsArticleId'], ['news_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thesisId'], ['theses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_relevance_newsArticleId'), 'news_relevance', ['newsArticleId'], unique=False)
    op.create_index(op.f('ix_news_relevance_thesisId'), 'news_relevance', ['thesisId'], unique=False)
    op.create_table('thesis_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thesisId', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('signalName', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('currentValue', sa.String(length=255), nullable=True),
    sa.Column('previousValue', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thesisId'], ['theses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thesis_signals_thesisId'), 'thesis_signals', ['thesisId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thesis_signals_thesisId'), table_name='thesis_signals')
    op.drop_table('thesis_signals')
    op.drop_index(op.f('ix_news_relevance_thesisId'), table_name='news_relevance')
    op.drop_index(op.f('ix_news_relevance_newsArticleId'), table_name='news_relevance')
    op.drop_table('news_relevance')
    op.drop_index(op.f('ix_evidence_timestamp'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_thesisId'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_symbol'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_evaluations_thesisId'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_evaluatedAt'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_theses_watchlistItemId'), table_name='theses')
    op.drop_index(op.f('ix_theses_userId'), table_name='theses')
    op.drop_table('theses')
    op.drop_index(op.f('ix_watchlist_items_watchlistId'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_symbol'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_watchlist_evaluations_watchlistId'), table_name='watchlist_evaluations')
    op.drop_table('watchlist_evaluations')
    op.drop_index(op.f('ix_watchlists_userId'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_news_articles_symbol'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_market_snapshots_timestamp'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_symbol'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_fundamental_snapshots_timestamp'), table_name='fundamental_snapshots')
    op.drop_index(op.f('ix_fundamental_snapshots_symbol'), table_name='fundamental_snapshots')
    op.drop_table('fundamental_snapshots')
    # ### end Alembic commands ###
